### PR TITLE
Linsen test

### PR DESCRIPTION
**Pull request by forest5013**
@FreeTymeKiyan @lvyb @hustldw @kuangami

### CODE REVIEW

**Comment by kuangami** [comment]
looks good

**Comment by hustldw** [comment]
Looks pretty good. Is that possible to increase the efficiency?

**Comment by lvyb** [comment]
nice!

**Comment by lvyb** [comment]
A suggestion though, can we add the problem description in the committed file so we don't need to go back and look up the problem. Easier for reviewing.

**Comment by JoannaCode** [comment]
Agree～

**Comment by FreeTymeKiyan** [comment]
@forest5013 thanks for the example!
@lvyb great suggestion! 
Please refer to my previous Java code for better format [WordLadder2](https://github.com/FreeTymeKiyan/LeetCode-Sol-Res/blob/master/Hard/WordLadder2.java)

**Comment by FreeTymeKiyan** [comment]
The very basic way for Two Sum is to do two nested for-loops, one to iterate through the given array, one to search for the other number. The first loop is necessary, nothing can be improved on that. The only improvement possible is the second loop, to reduce the O(n) iteration to lower complexity, O(logn), or even O(1). That's where map comes in. Hope this can answer your question @hustldw .

So try to come with the intuitive, basic solution first, although it might not be perfect. Then find where it can be improved, including efficiency, logic, variable usage and even format. I believe this kind of thinking will help you guys greatly in an interview.

**Comment by FreeTymeKiyan** [comment]
LGTM

**Pull request merged**
