### PR TITLE
Add solution for 045 jump game II

### PR DESCRIPTION
**Pull request by sasa150**
rt

### CODE REVIEW

**Comment by sasa150** [comment]
any comments?

**Comment by forest5013** [comment]
DP is also very common in leetcode

**Comment by sasa150** [comment]
@forest5013 Is DP necessary in this problem..?

**Comment by forest5013** [comment]
@sasa150 you can try without DP to see whether it's over the time limit

**Comment by sasa150** [comment]
@forest5013 my solution did not use DP, and got AC...

**Comment by FreeTymeKiyan** [comment]
LGTM

**Pull request merged**
