### PR TITLE
Shuna12

### PR DESCRIPTION
**Pull request by JoannaCode**
@FreeTymeKiyan  Please ignore MinimumWindowSubstring.

### CODE REVIEW

**Comment by FreeTymeKiyan** [comment]
looks good!

**Comment by JoannaCode** [comment]
@FreeTymeKiyan  Created  a new branch shuna_12 for 12

**Comment by FreeTymeKiyan** [comment]
you still need to commit only one file for this branch

**Comment by JoannaCode** [comment]
This branch can be delete~ those 2 problem have their own branch.

2016-03-31 10:58 GMT-07:00 Kiyan <notifications@github.com>:

**Comment by FreeTymeKiyan** [comment]
didn't see the branch for MinimumWindowSubstring

**Comment by JoannaCode** [comment]
You have already merged that branch  #98 ~

2016-03-31 11:03 GMT-07:00 Kiyan <notifications@github.com>:

**Comment by FreeTymeKiyan** [comment]
OK, great! I'll close this one.

**Pull request closed without merging**
