### PR TITLE
finishd 144

### PR DESCRIPTION
**Pull request by JoannaCode**
@xliu45

### CODE REVIEW

**Comment by xliu45** [comment]
Looks good. I am not familiar with JAVA, so I am not sure if you need to "delete" after you use "new" in  your main function. Or it might cause memory leakage.

**Comment by FreeTymeKiyan** [comment]
@xliu45 No worries, Java has garbage collection system to manage it. 
@JoannaCode Again, please fix the indentation. What kind of IDE or Text Editor you use, BTW? Is it that hard to config?

**Comment by xliu45** [comment]
@FreeTymeKiyan Thank you for reply

**Comment by yanjiao** [comment]
This is an automatically generated message.

yanjiao@yahoo-inc.com is no longer with Yahoo! Inc.

Your message will not be forwarded.

If you have a sales inquiry, please email yahoosales@yahoo-inc.com and someone will follow up with you shortly.

If you require assistance with a legal matter, please send a message to legal-notices@yahoo-inc.com

Thank you!

**Comment by JoannaCode** [comment]
@FreeTymeKiyan  I useS Eclipse. So it can automatic generate the main function(which have tab included) and  the tab in each line. So I need delete each line's tab and use space. It looks well in Eclipse.

**Pull request merged**
