### PR TITLE
Add 202 Happy Number

### PR DESCRIPTION
**Pull request by FreeTymeKiyan**
@forest5013 @hustldw @JoannaCode @kuangami @lvyb @sasa150 @xliu45 
2 solutions. This one is simple but fun!

### CODE REVIEW

**Comment by forest5013** [comment]
first solution is intersting

**Comment by FreeTymeKiyan** [comment]
@xliu45 yeah, add problem description so that everyone else don't need to go back to the website. 
Number is not important, it's already included in the file name.

**Comment by xliu45** [comment]
@FreeTymeKiyan 
Fair enough. 
I suggested that since the other codes are in that format including index number.

**Comment by FreeTymeKiyan** [comment]
@xliu45 I got what you mean. For Java, the import clauses always goes to the top. The `/** ... */` comment is always one line above the class or method, so that the documentation can show in IDE and can be auto-generated.

**Comment by xliu45** [comment]
I see, good point

On Saturday, March 5, 2016, Kiyan <notifications@github.com> wrote:

> @xliu45 <https://github.com/xliu45> I got what you mean. For Java, the
> import clauses always goes to the top. The /** ... */ comment is always
> one line above the class or method, so that the documentation can show in
> IDE and can be auto-generated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeTymeKiyan/LeetCode-Sol-Res/pull/10#issuecomment-192793348>
> .
>


-- 
Xinyu Liu, Research Assistant
Department of Electrical and Computer Engineering
Houston, TX, 77204-4005

**Comment by JoannaCode** [comment]
The first solution is interesting.

**Comment by FreeTymeKiyan** [comment]
@forest5013 Please help me merge it.

**Pull request merged**
