### PR TITLE
141 Linked List Cycle

### PR DESCRIPTION
**Pull request by lvyb**
Very simple one!

### CODE REVIEW

**Comment by hustldw** [comment]
looks good!

**Comment by forest5013** [comment]
looks good. Fast and Slow pointers are very common in link list problems.

**Comment by FreeTymeKiyan** [comment]
:+1:

**Comment by xliu45** [comment]
looks good!
It is classic instead of simple.

**Comment by FreeTymeKiyan** [comment]
I will merge it for now. Please refer to closed pull request if you are still interested.

**Pull request merged**
