### PR TITLE
Add 199 Binary Tree Right Side View

### PR DESCRIPTION
**Pull request by lvyb**
@sasa150  @FreeTymeKiyan  @JoannaCode  @xliu45  @hustldw @forest5013

### CODE REVIEW

**Comment by FreeTymeKiyan** [comment]
Please do NOT merge every time, that makes the commit history very ugly. 
You should create a new branch for a new problem. Old branches will be deleted.

**Comment by lvyb** [comment]
ok, starting from next one .

**Comment by xliu45** [comment]
Looks good

**Comment by forest5013** [comment]
good

**Comment by FreeTymeKiyan** [comment]
LGTM

**Pull request merged**
